apiVersion: v1
kind: Service
metadata:
  name: banking-application
  labels:
    app: banking
spec:
  type: LoadBalancer
  selector:
    app: banking
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banking-application
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: banking.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: banking-application
                port:
                  number: 80
