apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-api
  labels:
    app: banking-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-api
  template:
    metadata:
      labels:
        app: banking-api
    spec:
      containers:
        - name: api
          image: ghcr.io/example/banking-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: BANKING_STORAGE_MODE
              value: jdbc
            - name: BANKING_JDBC_URL
              value: jdbc:mysql://banking-mysql:3306/banking?useSSL=true&requireSSL=true&serverTimezone=UTC
            - name: BANKING_API_PORT
              value: "8080"
            - name: BANKING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: banking-config
                  key: BANKING_DB_USER
            - name: BANKING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-config
                  key: BANKING_DB_PASSWORD
            - name: BANKING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: banking-config
                  key: BANKING_API_KEY
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: banking-api
  labels:
    app: banking-api
spec:
  type: ClusterIP
  selector:
    app: banking-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: banking-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: banking-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
